// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdmbnlkvgeirwktpztad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkbWJubGt2Z2VpcndrdHB6dGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzY5NTQsImV4cCI6MjA2MjAxMjk1NH0.5hGnOP2ydTDp4ZqOVUPf-44E8_RhEFa0eE3eyhLuxhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);